server:
  port: ${APP_PORT}
spotify:
  client-id: ${CLIENT_ID}
  client-secret: ${CLIENT_SECRET}
  redirect-uri: ${REDIRECT_URI}
client:
  audio-tag-manager-url: ${AUDIO_TAG_MANAGER_URL}
spring:
  cloud.stream:
    function:
      definition:
        "produceSpotifyTracks;/
        produceTracksLiked;/
        producePlaylistCreated;/
        producePlaylistDeleted;/
        producePlaylistItemAdded"
      bindings:
        produceSpotifyTracks-out-0: spotify-track-created
        produceTracksLiked-out-0: liked-tracks
        producePlaylistCreated-out-0: playlist-created
        producePlaylistDeleted-out-0: playlist-deleted
        producePlaylistItemAdded-out-0: playlist-item-added
    bindings:
      spotify-track-created:
        destination: ${KAFKA_SPOTIFY_TRACK_TOPIC:spotify-track-created}
      liked-tracks:
        destination: ${KAFKA_TRACK_LIKED_TOPIC:track-liked}
      playlist-created:
        destination: ${KAFKA_PLAYLIST_CREATED_TOPIC:playlist-created}
      playlist-deleted:
        destination: ${KAFKA_PLAYLIST_DELETED_TOPIC:playlist-deleted}
      playlist-item-added:
        destination: ${KAFKA_PLAYLIST_ITEM_ADDED_TOPIC:playlist-item-added}
    default-binder: kafka
    kafka:
      binder:
        brokers: ${KAFKA_SERVER}