server:
  port: ${APP_PORT}
spotify:
  client-id: ${CLIENT_ID}
  client-secret: ${CLIENT_SECRET}
  redirect-uri: ${REDIRECT_URI}
client:
  audio-tag-manager-url: ${AUDIO_TAG_MANAGER_URL}
spring:
  cloud.stream:
    function:
      definition: produceSpotifyTracks;produceTracksLikedMessage
      bindings:
        produceSpotifyTracks-out-0: spotify-track
        produceTracksLikedMessage-out-0: liked-tracks
    bindings:
      spotify-track:
        destination: ${KAFKA_SPOTIFY_TRACK_TOPIC}
      liked-tracks:
        destination: ${KAFKA_TRACK_LIKED_TOPIC}
    default-binder: kafka
    kafka:
      binder:
        brokers: ${KAFKA_SERVER}